apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: vehicule-ns
type: Opaque
stringData:
  url: postgresql://postgres:postgres@postgresql:5432/fleet
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: conducteur-ns
type: Opaque
stringData:
  url: postgresql://postgres:postgres@postgresql:5432/fleet
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: maintenance-ns
type: Opaque
stringData:
  url: postgresql://postgres:postgres@postgresql:5432/fleet
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: localisation-ns
type: Opaque
stringData:
  url: postgresql://postgres:postgres@postgresql:5432/fleet
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: evenement-ns
type: Opaque
stringData:
  url: postgresql://postgres:postgres@postgresql:5432/fleet