apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-service
  namespace: maintenance-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintenance-service
  template:
    metadata:
      labels:
        app: maintenance-service
    spec:
      containers:
      - name: maintenance-service
        image: maintenance-service:latest
        imagePullPolicy: Never

        # === VARIABLES D'ENVIRONNEMENT ===
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"

        ports:
        - containerPort: 3002
          protocol: TCP

        # === READINESS PROBE ===
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3

        # === LIVENESS PROBE ===
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3

      restartPolicy: Always
