auth:
  username: utilisateur_flotte
  password: archi_distribuée
  database: flotte_db

primary:
  persistence:
    enabled: true
    size: 2Gi                   

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

architecture: standalone
